---
- name: encryption
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
      hereorthere: "present"
  vars_files:
      - ~/cred.zon
  tasks:
      - debug:
          var: ec2_access_key


