---
- name: intro to looping
  hosts: localhost
  gather_facts: no

  vars:
      ethlist: ["eth0", "eth1", "eth2", "eth3"]
  tasks:
      - name: tiny loop
        debug:
            msg: "the ethernet is: {{ item }}"
        loop: "{{ ethlist }}"
      - name: sec loop
        debug:
            msg: "the ips are: {{ item }}"
        loop: "{{ iplist }}"
        vars:
           iplist: ["10.10.0.1", "10.0.0.2"]
