---
- name: Thursday morning challenge
  hosts: bender
  connection: ssh
  gather_facts: no
  become: yes
  vars_prompt:
      - name: "mc_server_link"
        prompt: "url link pls"
        default: https://launcher.mojang.com/v1/objects/3cf24a8694aca6267883b17d934efacc5e44440d/server.jar
  tasks:
  - debug:
      msg: "{{ mc_server_link }}"  
  - name: Install apps for minecraft server
    block:
        - name: Install additional apps via apt
          apt:
            name:
               - fail2ban # enables the linux host to ban IPs with suspicious SSH activity
            state: present
    rescue:
        - name: Rescue task
          apt:
              state: absent
              name: 
                - fail2ban
          become: yes
        - name: task failed
          fail:
              msg: "task failed. Rollback complete"

  - name: Copy fail2ban (ssh protection)
    copy:
      content: "get off my dang server"
      dest: /etc/fail2ban/jail.conf
    notify: Restart_fail2ban
  handlers:
  - name: Restart_fail2ban
    service:
      name: fail2ban
      state: restarted

  - name: Add a directory
    file:
      path: "/home/{{ ansible_user }}/minecraft"
      state: directory
      
  - name: Download minecraft server
    get_url:
      url: "{{ mc_server_link }}"
      dest: /home/{{ ansible_user }}/minecraft/minecraft_server.jar
