---
- name: Tuesday Challenge
  hosts: planetexpress:!farnsworth 
  connection: ssh
  gather_facts: yes

  tasks:
     - apt:
         name: sl
         state: present
       name: using apt to install sl        
       register: result  # <-- this is new! "register" is creating a variable named "result" which contains the output from this task
       become: true

     - name: print out the variable named "result"                  
       debug: # the debug module is similar to print() in python-- it prints stuff out!       
          var: result # displaying the value of the variable "result"            
