download_url: https://galaxy.ansible.com/download/netapp-elementsw-21.7.0.tar.gz
format_version: 1.0.0
name: elementsw
namespace: netapp
server: https://galaxy.ansible.com/api/
signatures: []
version: 21.7.0
version_url: https://galaxy.ansible.com/api/v2/collections/netapp/elementsw/versions/21.7.0/
