---
# handlers file for /home/student/galaxy/roles/challenge
# This will ONLY run if the associated tasks run
  # no matter how many times called these tasks
  # will ONLY run once
  - name: restart_apache
    service:
      name: apache2
      state: restarted
    listen: restart_webservices

  ## this is new, restarts MySQL
  - name: restart_mysql
    service:
      name: mysql
      state: restarted
    listen: restart_webservices
